const API_BASE=location.hostname.endsWith("github.io")?"https://api.116.212.72.79.nip.io":"";
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const project=document.getElementById("explorer-project"),state=document.getElementById("seed-universe-state"),summary=document.getElementById("seed-universe-summary"),papers=document.getElementById("seed-paper-list"),queries=document.getElementById("seed-query-options");
const roleLabel=x=>({"CORE_PHENOMENON":"Fenomena inti","PUBLIC_SECTOR_CONTEXT":"Konteks sektor publik","DECISION_APPLICATION":"Keputusan / aplikasi","RESPONSIBILITY_EXPLAINABILITY":"Responsibility / explainability","LANDSCAPE_REVIEW":"Pemetaan landscape"})[x]||"Istilah dari seed";
async function loadSeedUniverse(){
 if(!project.value)return;state.textContent="LOADING";
 try{const r=await fetch(`${API_BASE}/api/projects/${encodeURIComponent(project.value)}/seed-universe`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json();
 renderProgressiveFunnel({sessions:[]});
 state.textContent=x.observed_universe_state||"UNKNOWN";state.className=`state ${x.observed_universe_state==="OBSERVED"?"green":"gray"}`;
 summary.innerHTML=`<strong>${esc(x.seed_count)} seed paper</strong> · Research Universe: <strong>${esc(x.observed_universe_state)}</strong><br>${esc(x.explanation)}<br><small>Scientific decision: false · Seed ≠ Universe · Discovery ≠ Evidence</small>`;
 papers.innerHTML=(x.seeds||[]).map((p,i)=>`<article class="explorer-seed"><strong>${i+1}. ${esc(p.title)}</strong><p>${esc(p.publication_year||"TIDAK_TERCATAT")} · ${esc(p.venue_name||"TIDAK_TERCATAT")} · ${esc(p.access_level||"TIDAK_TERCATAT")}</p><details><summary>Canonical detail</summary><small>Work: ${esc(p.work_id)} · source: ${esc(p.source_key||"TIDAK_TERCATAT")}</small></details></article>`).join("")||'<div class="callout">Seed paper TIDAK_TERSEDIA.</div>';
 const groups={};(x.query_family_candidates||[]).forEach(q=>(groups[q.family_role]??=[]).push(q));
 queries.innerHTML=Object.entries(groups).map(([role,items])=>`<section class="query-family"><h4>${esc(roleLabel(role))}</h4><p class="explorer-muted">Opsi untuk memperluas pencarian; bukan scope yang ditetapkan mesin.</p>${items.map(q=>`<article class="explorer-query"><div><strong>${esc(q.label)}</strong><code>${esc(q.candidate_query)}</code><span class="state gray">NOT APPROVED</span></div><p><strong>Mengapa ditampilkan?</strong> ${esc(q.why_shown)}</p><p><strong>Paper pemicu:</strong> ${q.seed_titles.map(esc).join(" · ")}</p><p><strong>Yang perlu HUMAN periksa:</strong> ${esc(q.human_check)}</p><details><summary>Canonical provenance</summary><small>Work ID: ${q.seed_work_ids.map(esc).join(" · ")}</small></details></article>`).join("")}</section>`).join("")||'<div class="callout">Query option TIDAK_TERSEDIA.</div>';
 }catch(e){state.textContent="TIDAK_TERSEDIA";summary.textContent=`Seed projection tidak tersedia: ${e.message}`;papers.innerHTML="";queries.innerHTML="";}
}
fetch(`${API_BASE}/api/context`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(rows=>{project.innerHTML=rows.map(x=>`<option value="${esc(x.project_id)}">${esc(x.profile_name)} / ${esc(x.project_name)}</option>`).join("");project.onchange=loadSeedUniverse;loadSeedUniverse();}).catch(e=>{project.innerHTML='<option>Context unavailable</option>';summary.textContent=`Context tidak tersedia: ${e.message}`;});
const benchResult=document.getElementById("bench-result"),benchPreview=document.getElementById("bench-preview");
if(benchPreview)benchPreview.onclick=()=>{
 const total=document.getElementById("bench-total").value,captured=document.getElementById("bench-captured").value,query=document.getElementById("bench-query").value.trim(),time=document.getElementById("bench-time").value,params=document.getElementById("bench-params").value.trim();
 const members=document.getElementById("bench-members").value.split(/\n+/).map(x=>x.trim()).filter(Boolean);
 if(!query||!time){benchResult.innerHTML="<strong>INCOMPLETE</strong> · Exact query dan waktu pencarian diperlukan sebelum benchmark dapat dibandingkan.";return;}
 const parity=params?"PARITY_REQUIRES_REVIEW":"NON_PARITY_COMPARISON";
 benchResult.innerHTML="<strong>HUMAN observation draft</strong><br>Provider reported: <strong>"+esc(total||"TIDAK_TERSEDIA")+"</strong> · HUMAN captured: <strong>"+esc(captured||"TIDAK_TERSEDIA")+"</strong> · Member identifiers: <strong>"+members.length+"</strong><br>Comparison readiness: <strong>"+parity+"</strong><br>Overlap / HUMAN-only / Machine-only: <strong>TIDAK_TERSEDIA</strong> sampai machine observation dan member reconciliation tersedia.<br><small>Local preview only · no canonical write · scientific decision: false</small>";
};

const initialQuery=document.getElementById("initial-human-query"),initialPreview=document.getElementById("initial-query-preview"),initialResult=document.getElementById("initial-query-result");
if(initialPreview)initialPreview.onclick=()=>{
 const q=initialQuery.value.trim();
 if(!q){initialResult.innerHTML="<strong>INCOMPLETE</strong> · Query awal HUMAN diperlukan.";return;}
 initialResult.innerHTML="<strong>Baseline preview:</strong> "+esc(q)+"<br><small>Origin: HUMAN_PROVIDED · approval state: LOCAL_PREVIEW · canonical write: false · scientific decision: false · historical J14 query unchanged</small>";
};

function renderProgressiveFunnel(x){
 const observations=(x.sessions||[]).flatMap(s=>s.observations||[]);
 const retrieved=observations.length;
 const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};
 set("f-provider","TIDAK_TERSEDIA");
 set("f-retrieved",retrieved);
 set("f-remaining","TIDAK_TERSEDIA");
 set("f-dedup",retrieved?"TIDAK_TERCATAT":"NOT_RUN");
 set("f-screened",retrieved?"TIDAK_TERCATAT":"NOT_RUN");
 set("f-human",retrieved?"TIDAK_TERCATAT":"NOT_RUN");
 set("f-project","TIDAK_TERSEDIA");
}

const trialAdvice=document.getElementById("trial-advice"),trialPaperCount=document.getElementById("trial-paper-count"),trialState=document.getElementById("trial-state"),trialCoverage=document.getElementById("trial-coverage"),trialYears=document.getElementById("trial-years"),trialAreas=document.getElementById("trial-areas"),trialAreaDetail=document.getElementById("trial-area-detail"),trialPapers=document.getElementById("trial-papers"),trialBlindspots=document.getElementById("trial-blindspots"),trialDecisions=document.getElementById("trial-decisions"),trialDecisionState=document.getElementById("trial-decision-state");
let trialWhy=null,trialPaperMap=new Map(),selectedTrialArea=null;
const deepDiveTitle=document.getElementById("deep-dive-title"),deepDiveState=document.getElementById("deep-dive-state"),deepDiveSummary=document.getElementById("deep-dive-summary"),deepDiveOpportunities=document.getElementById("deep-dive-opportunities"),deepDiveInspect=document.getElementById("deep-dive-inspect"),deepDiveCopilot=document.getElementById("deep-dive-copilot");
function buildCopilotHandoff(t){
 const learning=document.getElementById("trial-learning")?.value.trim()||"";return {schema:"GFPROJCLAW_EXPLORER_HANDOFF_V0",source:"Research Explorer",query:'"digital government" "artificial intelligence" "public services"',time_boundary:"2022–2026",area:t.area,path:t.path||[t.area],why:t.why_shown,supporting_observation:t.supporting_observation,verification:t.verification,member_count:(t.members||[]).length,member_ids:(t.members||[]).slice(0,30).map(x=>x.openalex_id),human_learning_note:learning,scientific_decision:false,canonical_write:false};
}
function gapOpportunities(members,path){const subs=computeSubareas(members,path).filter(([term])=>!["review","role","case","through","study","analysis"].includes(term)).slice(0,5);return subs.map(([term,n],i)=>({id:`GO-${i+1}`,term,count:n,observation:`${n} dari ${members.length} paper pada subset ini memuat istilah “${term}” pada judul.`,why:`“${term}” muncul sebagai konteks berulang di dalam jalur HUMAN ${path.join(" → ")}.`,limitation:"Sinyal berbasis judul/metadata; abstrak, metode, konteks substantif, dan full text belum diverifikasi.",verification:`Periksa paper anggota yang memuat “${term}” dan bandingkan dengan paper subset yang tidak memuat istilah tersebut.`}));}
function updateDeepDive(t){selectedTrialArea=t;if(!t)return;const path=t.path||[t.area],members=t.members||[],label=path.join(" → ");const years=members.map(x=>(trialPaperMap.get(x.openalex_id)||x).publication_year).filter(Boolean),yr=years.length?`${Math.min(...years)}–${Math.max(...years)}`:"TIDAK_TERCATAT",subs=computeSubareas(members,path).slice(0,6),opps=gapOpportunities(members,path);deepDiveTitle.textContent=`Pendalaman: ${label}`;deepDiveState.textContent="PRELIMINARY";deepDiveState.className="state blue";deepDiveSummary.innerHTML=`<strong>Evidence Summary · ${esc(members.length)} paper</strong><br>Subset ini dipilih HUMAN melalui <strong>${esc(label)}</strong> dan mencakup publikasi ${esc(yr)}. Konteks judul yang berulang berikutnya: ${subs.length?subs.map(([x,n])=>`${esc(x)} (${n})`).join(", "):"belum ada sinyal berulang yang cukup"}.<br><strong>Batas bukti:</strong> ringkasan ini berbasis metadata/judul. Abstrak, metode, unit analisis, temuan, dan full text belum diverifikasi.<br><small>Ini evidence summary awal, bukan kesimpulan literatur.</small>`;if(deepDiveOpportunities)deepDiveOpportunities.innerHTML=`<h4>Gap Opportunities · opsi untuk HUMAN</h4>${opps.length?opps.map(o=>`<article class="gap-card"><div><span class="state gray">${esc(o.id)}</span> <strong>${esc(o.term)}</strong></div><p><strong>Observasi:</strong> ${esc(o.observation)}</p><p><strong>WHY:</strong> ${esc(o.why)}</p><p><strong>Yang belum diketahui:</strong> ${esc(o.limitation)}</p><p><strong>Verifikasi berikutnya:</strong> ${esc(o.verification)}</p><button class="secondary-action gap-select" type="button" data-term="${esc(o.term)}">Pilih opportunity ini</button></article>`).join(""):"<div class=\"callout\">Belum ada gap opportunity berbasis sinyal judul yang cukup. Periksa paper atau pilih konteks lain.</div>"}<small>Opportunity bukan research gap, novelty, atau rekomendasi ilmiah. HUMAN memilih apakah sinyal layak ditelusuri.</small>`;deepDiveOpportunities?.querySelectorAll(".gap-select").forEach(b=>b.onclick=()=>{const term=b.dataset.term;trialDecisionState.innerHTML=`<strong>Gap Opportunity dipilih HUMAN: ${esc(label)} → ${esc(term)}</strong><br>Langkah berikutnya: verifikasi supporting papers, counter-evidence, abstrak/metode/konteks sebelum menyebutnya research gap.<br><small>scientific decision: false · canonical write: false</small>`;});deepDiveInspect.disabled=false;deepDiveCopilot.disabled=false;}
if(deepDiveInspect)deepDiveInspect.onclick=()=>document.getElementById("trial-papers")?.scrollIntoView({behavior:"smooth",block:"start"});
if(deepDiveCopilot)deepDiveCopilot.onclick=()=>{if(!selectedTrialArea)return;sessionStorage.setItem("gfprojclaw-explorer-handoff",JSON.stringify(buildCopilotHandoff(selectedTrialArea)));window.location.href="index.html?from=explorer&view=handoff";};
function renderTrialPapers(members){
 const shown=(members||[]).slice(0,30);if(trialPaperCount)trialPaperCount.textContent=`${shown.length} / ${(members||[]).length} DITAMPILKAN`;
 trialPapers.innerHTML=shown.map(m=>{const p=trialPaperMap.get(m.openalex_id)||m;return `<article class="explorer-seed"><strong>${esc(p.title||"JUDUL TIDAK_TERSEDIA")}</strong><p>${esc(p.publication_year||"TIDAK_TERCATAT")} · ${esc(p.venue||"VENUE TIDAK_TERCATAT")} · DOI ${esc(p.doi||"TIDAK_TERSEDIA")}</p><div class="trial-paper-links">${p.source_url?`<a href="${esc(p.source_url)}" target="_blank" rel="noopener">OpenAlex ↗</a>`:""}${p.doi_url?`<a href="${esc(p.doi_url)}" target="_blank" rel="noopener">DOI ↗</a>`:""}</div><small>Abstrak: ${esc(p.abstract_state||"BELUM_DIAMBIL_DALAM_UJI_INI")} · Teks lengkap: ${esc(p.full_text_state||"BELUM_DIPERIKSA")}</small></article>`}).join("")||'<div class="callout">Member paper TIDAK_TERSEDIA.</div>';
}
const trialDrill=document.getElementById("trial-drilldown"),trialSubareas=document.getElementById("trial-subareas"),trialBreadcrumb=document.getElementById("trial-breadcrumb"),trialDrillCount=document.getElementById("trial-drill-count"),trialStopDrill=document.getElementById("trial-stop-drill"),trialResetDrill=document.getElementById("trial-reset-drill");
let drillPath=[],drillMembers=[];
const drillStop=new Set(["the","and","for","with","from","this","that","using","use","into","based","study","analysis","research","artificial","intelligence","digital","government","public","services","service","of","in","on","to","a","an"]);
function titleTerms(title){return [...new Set((String(title||"").toLowerCase().match(/[a-z][a-z-]{2,}/g)||[]).filter(x=>!drillStop.has(x)))];}
function computeSubareas(members,path){const counts=new Map(),chosen=new Set(path);for(const m of members){const p=trialPaperMap.get(m.openalex_id)||m;for(const term of titleTerms(p.title))if(!chosen.has(term))counts.set(term,(counts.get(term)||0)+1);}return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).filter(([,n])=>n>=3).slice(0,20);}
function renderAdviceForContext(){if(!drillPath.length)return;const label=drillPath.join(" → "),members=drillMembers,venues=[...new Set(members.map(x=>(trialPaperMap.get(x.openalex_id)||x).venue).filter(Boolean))].slice(0,5),years=members.map(x=>(trialPaperMap.get(x.openalex_id)||x).publication_year).filter(Boolean),yr=years.length?`${Math.min(...years)}–${Math.max(...years)}`:"TIDAK_TERCATAT";if(trialAdvice)trialAdvice.innerHTML=`<h3>Saran Riset · ${esc(label)}</h3><div class="advice-grid"><div class="advice-card"><strong>Apa yang kami amati</strong>${esc(members.length)} paper berada pada intersection jalur HUMAN “${esc(label)}” berdasarkan istilah judul, periode ${esc(yr)}. Contoh venue: ${esc(venues.join(", ")||"TIDAK_TERCATAT")}.</div><div class="advice-card"><strong>Mengapa ini mungkin penting</strong>Jalur ini dipilih HUMAN dari struktur yang teramati. Frekuensi/intersection tidak membuktikan relevansi, gap, atau novelty.</div><div class="advice-card"><strong>Apa yang perlu diperiksa berikutnya</strong>Periksa variasi penggunaan istilah, tahun, venue, abstrak, metode, dan konteks pada paper anggota sebelum penggunaan ilmiah.</div><div class="advice-card"><strong>Pertanyaan untuk Anda</strong>Apakah kedalaman “${esc(label)}” sudah cukup untuk dibawa ke reasoning lebih lanjut, atau Anda perlu kembali dan memilih cabang lain?</div></div><small>Saran berasal dari subset corpus yang dapat ditelusuri; HUMAN tetap menentukan makna dan arah riset.</small>`;renderTrialPapers(members);const root=(trialWhy?.traces||[]).find(x=>x.area===drillPath[0]);if(root)updateDeepDive({...root,area:label,path:[...drillPath],members});trialAdvice.scrollIntoView({behavior:"smooth",block:"start"});}
function renderDrill(){trialDrill.hidden=false;trialBreadcrumb.innerHTML=`<strong>Semesta Riset</strong> → ${drillPath.map((x,i)=>`<button type="button" data-depth="${i}">${esc(x)}</button>`).join(" → ")}`;trialDrillCount.textContent=`${drillMembers.length} PAPER`;const subs=computeSubareas(drillMembers,drillPath);trialSubareas.innerHTML=subs.map(([term,n])=>`<button class="trial-area" type="button" data-term="${esc(term)}"><strong>${esc(term)}</strong><br><small>${esc(n)} paper pada subset ini</small></button>`).join("")||'<div class="callout">Tidak ada konteks lanjutan yang cukup sering teramati. Anda dapat meminta Saran Riset pada kedalaman ini.</div>';trialSubareas.querySelectorAll("button").forEach(b=>b.onclick=()=>drillInto(b.dataset.term));trialBreadcrumb.querySelectorAll("button").forEach(b=>b.onclick=()=>{const keep=drillPath.slice(0,Number(b.dataset.depth)+1);startDrillPath(keep);});}
function startDrillPath(path){const root=(trialWhy?.traces||[]).find(x=>x.area===path[0]);if(!root)return;let members=root.members||[];for(const term of path.slice(1))members=members.filter(m=>titleTerms((trialPaperMap.get(m.openalex_id)||m).title).includes(term));drillPath=path;drillMembers=members;renderDrill();renderTrialPapers(members);updateDeepDive({...root,area:path.join(" → "),path:[...path],members});}
function drillInto(term){startDrillPath([...drillPath,term]);trialAreaDetail.innerHTML=`<strong>JALUR HUMAN</strong> · ${drillPath.map(esc).join(" → ")}<br><strong>${esc(drillMembers.length)} paper</strong> pada intersection istilah judul ini.<br><small>Anda dapat masuk lebih dalam atau berhenti dan meminta Saran Riset.</small>`;}
function showTrialArea(term){const t=(trialWhy?.traces||[]).find(x=>x.area===term);if(!t)return;trialAreaDetail.innerHTML=`<strong>MENGAPA ${esc(term)}</strong><br>${esc(t.why_shown)}<br><strong>Observasi pendukung:</strong> ${esc(t.supporting_observation?.observed_title_count)} anggota tepat berdasarkan istilah pada judul.<br><small>Pilih sub-area untuk bergerak global → detail, atau berhenti pada kedalaman yang cukup bagi Anda.</small>`;startDrillPath([term]);if(trialAdvice)trialAdvice.innerHTML=`<h3>Saran Riset</h3><p>Belum ditampilkan. Eksplorasi sub-area terlebih dahulu, atau pilih <strong>“Cukup — berikan Saran Riset untuk konteks ini”</strong>.</p>`;renderTrialPapers(t.members||[]);}
if(trialStopDrill)trialStopDrill.onclick=renderAdviceForContext;
if(trialResetDrill)trialResetDrill.onclick=()=>{drillPath=[];drillMembers=[];trialDrill.hidden=true;trialAreaDetail.textContent="Pilih area global lain untuk memulai pendalaman.";};
async function loadResearchValueTrial(){
 if(!trialState)return;
 try{
  const [lr,wr,pr,cr]=await Promise.all(["landscape","why","papers","coverage"].map(x=>fetch(`${API_BASE}/api/trial/research-value/${x}`,{cache:"no-store"})));if([lr,wr,pr,cr].some(r=>!r.ok))throw new Error("payload uji tidak tersedia");
  const [l,w,p,c]=await Promise.all([lr.json(),wr.json(),pr.json(),cr.json()]);trialWhy=w;trialPaperMap=new Map((p.papers||[]).map(x=>[x.openalex_id,x]));
  trialState.textContent="SELURUH SEMESTA TERBATAS";trialState.className="state green";
  const cv=l.coverage||{};trialCoverage.innerHTML=`<strong>${esc(cv.raw_retrieved_count)} / ${esc(cv.provider_reported_total)} record mentah OpenAlex berhasil diambil</strong> · ${esc(cv.retrieved_count)} anggota setelah deduplikasi<br><small>Observasi provider yang dibatasi query/waktu · bukan jumlah relevan secara ilmiah · penulisan canonical: false</small>`;
  trialYears.innerHTML=Object.entries(l.year_landscape||{}).sort().map(([y,n])=>`<article class="trial-metric"><span>${esc(y)}</span><strong>${esc(n)}</strong></article>`).join("");
  trialAreas.innerHTML=(l.observed_areas||[]).map(a=>`<button class="trial-area" type="button" data-term="${esc(a.term)}"><strong>${esc(a.term)}</strong><br><small>${esc(a.observed_count)} observasi judul</small></button>`).join("");trialAreas.querySelectorAll("button").forEach(b=>b.onclick=()=>showTrialArea(b.dataset.term));
  const cov=c.coverage||{};trialBlindspots.innerHTML=`<strong>Diamati:</strong> ${esc((cov.searched_sources||[]).join(", "))}<br><strong>Belum dicari secara seluruh-semesta-terbatas:</strong> ${esc((cov.not_searched_sources||[]).join(", "))}<br>${esc(c.blind_spot_statement)}<br><small>Abstrak diambil: ${esc(cov.abstracts_retrieved)} · Teks lengkap diperiksa: ${esc(cov.full_text_checked)}</small>`;
  trialDecisions.innerHTML=(c.human_decision_options||[]).map(x=>`<button class="secondary-action" type="button" data-decision="${esc(x)}">${esc(x.replaceAll("_"," "))}</button>`).join("");trialDecisions.querySelectorAll("button").forEach(b=>b.onclick=()=>{trialDecisionState.innerHTML=`<strong>Refleksi scope HUMAN lokal: ${esc(b.dataset.decision)}</strong><br><small>Hanya pratinjau · tidak ada penulisan canonical · bukan keputusan ilmiah mesin.</small>`});
  if(l.observed_areas?.length)showTrialArea(l.observed_areas[0].term);
 }catch(e){trialState.textContent="TIDAK_TERSEDIA";trialCoverage.textContent=`Lanskap uji tidak tersedia: ${e.message}`;}
}
loadResearchValueTrial();

const acceptPreview=document.getElementById("accept-preview"),acceptResult=document.getElementById("accept-result");
if(acceptPreview)acceptPreview.onclick=()=>{
 const ids=["accept-landscape","accept-why","accept-trace","accept-limits"],passed=ids.filter(id=>document.getElementById(id)?.checked).length,rationale=document.getElementById("accept-rationale")?.value.trim()||"";
 if(passed<4||!rationale){acceptResult.innerHTML=`<strong>MENUNGGU</strong> · ${passed}/4 pemeriksaan penerimaan dikonfirmasi. Alasan HUMAN ${rationale?"tercatat":"wajib diisi"}.<br><small>GFPROJCLAW tidak dapat menyatakan sendiri bahwa dirinya bermanfaat secara ilmiah.</small>`;return;}
 acceptResult.innerHTML=`<strong>SIAP UNTUK CATATAN PENERIMAAN HUMAN</strong> · 4/4 pemeriksaan dikonfirmasi beserta alasan.<br><small>Pratinjau lokal ini bukan penerimaan canonical. HUMAN harus mencatat keputusan akhir secara eksplisit.</small>`;
};
