const API_BASE=location.hostname.endsWith("github.io")?"https://api.116.212.72.79.nip.io":"";
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const project=document.getElementById("explorer-project"),state=document.getElementById("seed-universe-state"),summary=document.getElementById("seed-universe-summary"),papers=document.getElementById("seed-paper-list"),queries=document.getElementById("seed-query-options");
async function loadSeedUniverse(){
 if(!project.value)return; state.textContent="LOADING";
 try{const r=await fetch(`${API_BASE}/api/projects/${encodeURIComponent(project.value)}/seed-universe`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const x=await r.json();
 state.textContent=x.observed_universe_state||"UNKNOWN";state.className=`state ${x.observed_universe_state==="OBSERVED"?"green":"gray"}`;
 summary.innerHTML=`<strong>${esc(x.seed_count)} seed paper</strong> · Research Universe: <strong>${esc(x.observed_universe_state)}</strong><br>${esc(x.explanation)}<br><small>Scientific decision: false · Seed ≠ Universe · Discovery ≠ Evidence</small>`;
 papers.innerHTML=(x.seeds||[]).map((p,i)=>`<article class="explorer-seed"><strong>${i+1}. ${esc(p.title)}</strong><p>${esc(p.publication_year||"NOT_RECORDED")} · ${esc(p.venue_name||"NOT_RECORDED")} · ${esc(p.access_level||"NOT_RECORDED")}</p><small>Work: ${esc(p.work_id)} · source: ${esc(p.source_key||"NOT_RECORDED")}</small></article>`).join("")||'<div class="callout">Seed paper NOT_AVAILABLE.</div>';
 queries.innerHTML=(x.query_family_candidates||[]).map(q=>`<article class="explorer-query"><div><strong>${esc(q.label)}</strong><code>${esc(q.candidate_query)}</code></div><span class="state gray">NOT APPROVED</span><p>${esc(q.why_shown)}</p><small>Dipicu oleh Work: ${q.seed_work_ids.map(esc).join(" · ")}</small></article>`).join("")||'<div class="callout">Query option NOT_AVAILABLE.</div>';
 }catch(e){state.textContent="NOT_AVAILABLE";summary.textContent=`Seed projection tidak tersedia: ${e.message}`;papers.innerHTML="";queries.innerHTML="";}
}
fetch(`${API_BASE}/api/context`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(rows=>{project.innerHTML=rows.map(x=>`<option value="${esc(x.project_id)}">${esc(x.profile_name)} / ${esc(x.project_name)}</option>`).join("");project.onchange=loadSeedUniverse;loadSeedUniverse();}).catch(e=>{project.innerHTML='<option>Context unavailable</option>';summary.textContent=`Context tidak tersedia: ${e.message}`;});