(() => {
  const dictionaries = {
    en: {
      today:"Today", journey:"Research Journey", opportunities:"Opportunities", evidence:"Evidence Explorer", evolution:"Knowledge Evolution", review:"Human Review", coverage:"Research Coverage", profile:"Profile", profiles:"Profiles & Projects", project:"Project", admin:"Admin Copilot", research:"Research Copilot", language:"Language", dark:"Dark", light:"Light", viewAll:"View all", searchPlaceholder:"Search papers, concepts, gaps…",
      todayTitle:"Today", todaySubtitle:"What changed, why it matters, and where HUMAN attention is useful.", recentChanges:"Recent Important Changes", stageGuide:"Research Stage Guide", topOpportunities:"Top Research Opportunities", latestPapers:"Latest Papers", radar:"Telegram Research Radar", persistedPapers:"Persisted Papers", humanDecisions:"HUMAN Decisions", knowledgeChanges:"Knowledge Changes", coverageContext:"Coverage Context", radarItems:"Radar Items", inspectMembers:"Inspect members →", canonicalMembers:"Canonical members", selectMetric:"Select a metric to inspect its exact members.", close:"Close", persistedWorksDetail:"Persisted works in selected project", humanDecisionsDetail:"Explicit persisted HUMAN decisions", knowledgeChangesDetail:"Persisted canonical ChangeEvents", radarDetail:"Read-only projections from ChangeEvent", loadingCoverage:"Loading persisted coverage context…", workflowGuideOnly:"Workflow guide only · no canonical stage status persisted", showRemainingStages:"Show R7–R16 guide", stageStatusReversible:"Status is reversible", allStages:"All stages", illustrativeBoundary:"ILLUSTRATIVE / NON-CANONICAL: every stage status, count, identifier, evidence trace, and suggested action below is demonstration data. Do not use it as scientific state."
    },
    id: {
      today:"Hari Ini", journey:"Perjalanan Riset", opportunities:"Peluang Riset", evidence:"Penjelajah Bukti", evolution:"Evolusi Pengetahuan", review:"Tinjauan HUMAN", coverage:"Cakupan Riset", profile:"Profil", profiles:"Profil & Proyek", project:"Proyek", admin:"Admin Copilot", research:"Research Copilot", language:"Bahasa", dark:"Gelap", light:"Terang", viewAll:"Lihat semua", searchPlaceholder:"Cari paper, konsep, gap…",
      todayTitle:"Hari Ini", todaySubtitle:"Apa yang berubah, mengapa penting, dan di mana perhatian HUMAN diperlukan.", recentChanges:"Perubahan Penting Terkini", stageGuide:"Panduan Tahap Riset", topOpportunities:"Peluang Riset Utama", latestPapers:"Paper Terbaru", radar:"Radar Riset Telegram", persistedPapers:"Paper Tersimpan", humanDecisions:"Keputusan HUMAN", knowledgeChanges:"Perubahan Pengetahuan", coverageContext:"Konteks Cakupan", radarItems:"Item Radar", inspectMembers:"Periksa anggota →", canonicalMembers:"Anggota canonical", selectMetric:"Pilih metrik untuk melihat anggota persisnya.", close:"Tutup", persistedWorksDetail:"Karya tersimpan dalam proyek yang dipilih", humanDecisionsDetail:"Keputusan HUMAN eksplisit yang tersimpan", knowledgeChangesDetail:"ChangeEvent canonical yang tersimpan", radarDetail:"Proyeksi read-only dari ChangeEvent", loadingCoverage:"Memuat konteks cakupan yang tersimpan…", workflowGuideOnly:"Hanya panduan alur kerja · belum ada status tahap canonical yang tersimpan", showRemainingStages:"Tampilkan panduan R7–R16", stageStatusReversible:"Status dapat berubah kembali", allStages:"Semua tahap", illustrativeBoundary:"ILUSTRATIF / NON-CANONICAL: setiap status tahap, angka, identifier, jejak bukti, dan tindakan yang disarankan di bawah adalah data demonstrasi. Jangan gunakan sebagai status ilmiah."
    }
  };
  const normalize = value => value === "id" ? "id" : "en";
  const current = () => "id";
  const t = key => dictionaries[current()][key] || dictionaries.en[key] || key;

  const stageNames = {
    en:["Research Intent","Research Landscape","Evidence Mapping","Problem Formulation","Gap Formation","Gap Falsification","Theory Positioning","Research Question","Conceptualization","Method Intelligence","Research Design","Contribution Formation","Novelty Challenge","Evidence & Argument Audit","Adversarial Review","Scholarly Positioning","Research Readiness"],
    id:["Tujuan Riset","Lanskap Riset","Pemetaan Bukti","Perumusan Masalah","Pembentukan Gap","Falsifikasi Gap","Penempatan Teori","Pertanyaan Riset","Konseptualisasi","Inteligensi Metode","Desain Riset","Pembentukan Kontribusi","Uji Kebaruan","Audit Bukti & Argumen","Tinjauan Adversarial","Penempatan Keilmuan","Kesiapan Riset"]
  };
  const stageName = index => stageNames[current()][index] || stageNames.en[index] || `R${index}`;
  const stageDescriptions = {
    id:[
      "Menetapkan tujuan, ruang lingkup, konteks, dan batas awal penelitian sebelum pencarian bukti diperluas.","Memahami struktur bidang, tema utama, aktor, istilah, dan wilayah literatur yang relevan.","Menghubungkan klaim, temuan, sumber, serta keterbatasan agar dasar bukti dapat ditelusuri.","Merumuskan masalah penelitian dari pola bukti, ketegangan, keterbatasan, dan kebutuhan yang teramati.","Menyusun kandidat gap dari bukti; gap belum dianggap terbukti sebelum diuji terhadap literatur pembanding.","Aktif mencari bukti yang membantah, mempersempit, atau menunjukkan bahwa kandidat gap telah dijawab.","Membandingkan lensa teoretis berdasarkan daya jelas, mekanisme, asumsi, dan kesesuaiannya dengan bukti.","Merumuskan pertanyaan yang spesifik, dapat diteliti, selaras dengan masalah, bukti, dan batas penelitian.","Mendefinisikan konstruk, hubungan, mekanisme, unit analisis, serta batas konseptual secara eksplisit.","Membandingkan metode, data, pengukuran, asumsi, validitas, dan keterbatasan yang digunakan literatur.","Menyusun desain yang menghubungkan pertanyaan, data, metode, analisis, validitas, etika, dan keterlaksanaan.","Merumuskan kontribusi potensial dan menunjukkan dengan jelas apa yang ditambah, diubah, atau diperjelas.","Menguji klaim kebaruan terhadap karya terdekat dan pencarian pembanding sebelum kebaruan diterima HUMAN.","Mengaudit apakah setiap argumen penting dapat ditelusuri ke bukti yang tepat beserta ketidakpastiannya.","Menguji riset dari sudut pandang kritis: alternatif penjelasan, counter-evidence, bias, dan titik lemah desain.","Menempatkan studi terhadap percakapan keilmuan dan menjelaskan hubungan dengan karya terdahulu tanpa melebihkan klaim.","Menilai kesiapan keseluruhan: pertanyaan, bukti, teori, metode, kontribusi, risiko, dan isu terbuka sebelum eksekusi."
    ],
    en:["Define the research purpose, scope, context, and initial boundaries before expanding evidence search.","Map the field structure, themes, actors, terminology, and relevant literature regions.","Connect claims, findings, sources, and limitations so the evidence basis remains traceable.","Formulate the research problem from evidence patterns, tensions, limitations, and observed needs.","Form a candidate gap from evidence; it is not established until tested against comparison literature.","Actively search for evidence that refutes, narrows, or shows the candidate gap has already been addressed.","Compare theoretical lenses by explanatory power, mechanisms, assumptions, and fit with evidence.","Formulate a specific, researchable question aligned with the problem, evidence, and research boundaries.","Define constructs, relationships, mechanisms, units of analysis, and conceptual boundaries explicitly.","Compare methods, data, measurement, assumptions, validity, and limitations used in the literature.","Design how question, data, method, analysis, validity, ethics, and feasibility fit together.","Formulate the potential contribution and specify what the study adds, changes, or clarifies.","Challenge novelty claims against nearest work and counter-search before HUMAN acceptance.","Audit whether important arguments trace to appropriate evidence with uncertainty visible.","Stress-test the research using alternative explanations, counter-evidence, bias, and design weaknesses.","Position the study in scholarly conversations and relate it to prior work without overstating claims.","Assess overall readiness across question, evidence, theory, method, contribution, risks, and open issues before execution."]
  };
  const stageDescription = index => stageDescriptions[current()][index] || stageDescriptions.en[index] || "";
  const stageShortDescriptions = {
    id:["Tetapkan tujuan, ruang lingkup, dan batas awal penelitian.","Kenali tema, istilah, karya utama, dan struktur bidang.","Petakan klaim ke bukti dan sumber yang dapat ditelusuri.","Temukan masalah dari pola, ketegangan, dan keterbatasan bukti.","Susun kandidat gap dari bukti; jangan menganggapnya terbukti.","Cari bukti yang dapat membantah atau mempersempit kandidat gap.","Bandingkan teori berdasarkan mekanisme dan daya jelas terhadap bukti.","Rumuskan pertanyaan yang spesifik, dapat diteliti, dan selaras dengan bukti.","Definisikan konstruk, hubungan, mekanisme, dan batas konseptual.","Bandingkan metode, data, pengukuran, validitas, dan keterbatasannya.","Hubungkan pertanyaan, data, metode, analisis, etika, dan keterlaksanaan.","Jelaskan apa yang berpotensi ditambah, diubah, atau diperjelas oleh studi.","Uji kebaruan terhadap karya terdekat dan pencarian pembanding.","Pastikan argumen penting dapat ditelusuri ke bukti dan ketidakpastian.","Uji alternatif penjelasan, counter-evidence, bias, dan kelemahan desain.","Tempatkan studi dalam percakapan keilmuan tanpa melebihkan klaim.","Periksa kesiapan pertanyaan, bukti, teori, metode, kontribusi, dan risiko."],
    en:["Set the purpose, scope, and initial research boundaries.","Identify themes, terminology, key works, and field structure.","Map claims to traceable evidence and sources.","Find the problem in evidence patterns, tensions, and limitations.","Form a candidate gap from evidence; do not treat it as established.","Seek evidence that can refute or narrow the candidate gap.","Compare theories by mechanisms and explanatory fit with evidence.","Formulate a specific, researchable question aligned with evidence.","Define constructs, relationships, mechanisms, and conceptual boundaries.","Compare methods, data, measurement, validity, and limitations.","Connect question, data, method, analysis, ethics, and feasibility.","Clarify what the study may add, change, or explain.","Challenge novelty against nearest work and comparison searches.","Ensure important arguments trace to evidence and uncertainty.","Test alternative explanations, counter-evidence, bias, and design weaknesses.","Position the study in scholarly conversations without overstating claims.","Check readiness across question, evidence, theory, method, contribution, and risk."]};
  const stageShortDescription = index => stageShortDescriptions[current()][index] || stageShortDescriptions.en[index] || "";

  function apply(root=document) {
    document.documentElement.lang=current();
    root.querySelectorAll("[data-i18n]").forEach(el => { el.textContent=t(el.dataset.i18n); });
    root.querySelectorAll("[data-i18n-placeholder]").forEach(el => { el.placeholder=t(el.dataset.i18nPlaceholder); });
    root.querySelectorAll("[data-language-select]").forEach(el => { el.value=current(); });
  }
  function setLanguage(value) { localStorage.setItem("gfprojclaw-language",normalize(value)); apply(); window.dispatchEvent(new CustomEvent("gfprojclaw-language-change",{detail:{language:current()}})); }
  window.GF_I18N={t,apply,setLanguage,current,stageName,stageDescription,stageShortDescription};
})();
